version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./downloads:/app/downloads
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_API_URL=${TELEGRAM_API_URL}
      - USE_LOCAL_API=${USE_LOCAL_API}
    restart: unless-stopped
    depends_on:
      - telegram-api

  telegram-api:
    image: aiogram/telegram-bot-api:latest
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    ports:
      - "8081:8081"
    restart: unless-stopped